CREATE TABLE IF NOT EXISTS names (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  origin_country TEXT,
  language TEXT,
  phonetic_hint TEXT,
  meaning TEXT
);
