export const tribes = [
    "Abayon", "Abua (Odual)", "Achipa (Achipawa)", "Adim", "Adun", "Affade", "Afizere", "Afo",
    "Agbo", "Akaju-Ndem (Akaji-Ndem)", "Akweya (Yace)", "Alago (Arago)", "Amo", "Anaguta", "Anang",
    "Andoni", "Angas", "Ankwei", "Anyima", "Attakar (ataka)", "Auyoka (Auyokawa)", "Awori", "Ayu",
    "Babur", "Bachama", "Bachere", "Bada", "Bade", "Bahumono", "Bakulung", "Bali", "Bambora (Bambarawa)",
    "Bambuko", "Bandi (Bandawa)", "Banka (Bankalawa)", "Banso (Panso)", "Bara (Barawa)", "Barke",
    "Baruba (Barba)", "Bashiri (Bashirawa)", "Bassa", "Batta", "Baushi", "Baya", "Bekwarra", "Bele (Buli, Belewa)",
    "Betso (Bete)", "Bette", "Bilei", "Bille", "Bina (Binawa)", "Bini", "Birom", "Bobua", "Boki (Nki)",
    "Bokkpy", "Bolo (Bolo-Bolo)", "Botlere", "Boma (Bomawa, Burmano)", "Bomboro", "Buduma", "Buji",
    "Buli", "Bunu", "Bura", "Burak", "Burma (Burmawa)", "Buru", "Buta (Butawa)", "Bwall", "Bwazza",
    "Challa", "Chama (Chamawa)", "Chamba", "Chamo", "Chibok (Chibbak)", "Chine (Chunuk)", "Chunvk",
    "Daa (Daawa)", "Dakkarkari", "Danda (Dandawa)", "Dangsa", "Daza (Dere, Derewa)", "Degema", "Deno (Denawa)",
    "Dghwede", "Diba", "Doemak (Dumuk)", "Ouguri", "Duka (Duku)", "Duma (Dumawa)", "Ebana (Ebani)",
    "Ebirra (Igbirra)", "Ebu", "Efik", "Egbema", "Egede (Igedde)", "Eggon", "Egun (Gu)", "Ejagham",
    "Ekajuk", "Eket", "Ekoi", "Engenni (Ngene)", "Epie", "Esan (Ishan)", "Etche", "Etolu (Etilo)",
    "Etsako", "Etung", "Etuno", "Palli", "Fulani (Fulbe)", "Fyam (Fyem)", "Fyer (Fer)", "Ga'anda",
    "Gade", "Galambi", "Gamergu-Mulgwa", "Gana (Ganawa)", "Ganawuri", "Gavako", "Gbedde", "Gengle",
    "Geji", "Gera (Gere, Gerawa)", "Geruma (Gerumawa)", "Gingwak", "Gira", "Gizigz", "Goemai", "Gokana",
    "Goni (Gonawa)", "Gora (Gorawa)", "Gorgoram", "Gokana", "Guhn", "Gwandara", "Gwari (Gbagyi)",
    "Gwom", "Gwon (Gwonawa)", "Gwoza (Waha)", "Gyem", "Hausa", "Higi", "Holma", "Hona", "Hyam", "Ibeno",
    "Ibibio", "Ichen", "Idoma", "Igala", "Igbo", "Ijaw", "Ijebu", "Ika", "Ikwere", "Ilaje", "Iman",
    "Ingassana (Gaam)", "Isoko", "Itsekiri", "Iwom", "Iyala (Iyalla)", "Izara (Izar, Izarek)", "Jaba",
    "Jahuna (Jahunawa)", "Jaku", "Jara (Jarawa)", "Jere (Jare, Jera, Jera, Jerawa)", "Jero", "Jibu",
    "Jidda-Abu", "Jimbin (Jimbinawa)", "Jirai", "Jju (Kaje)", "Jonjo (Jenjo)", "Jukun", "Kaba (Kabawa)",
    "Kadara", "Kafanchan", "Kagoro", "Ka-Iban", "Kalama", "Kaje (Kache)", "Kajuru (Kajurawa)", "Kaka",
    "Kamaku (Karnukawa)", "Kambari", "Kambu", "Kamo", "Kanakuru (Dera)", "Kanembu", "Kanikon", "Kantana",
    "Kanuri", "Karekare (Karaikarai)", "Karimjo", "Karuku", "Kaska (Kaskawa)", "Katab (Kataf)",
    "Kattab", "Kiballo (Kiwollo)", "Kilba", "Kirfi (Kirfawa)", "Koma", "Kona", "Koro (Kwaro)", "Kubi (Kubawa)",
    "Kudachano (Kudawa)", "Kugama", "Kulere (Kaler)", "Kunini", "Kurama", "Kurdul", "Kushi", "Kuteb",
    "Kutin", "Kwalla", "Kwami (Kwom)", "Kwanka (Kwankwa)", "Kwaro", "Kwato", "Kyenga (Kengawa)",
    "Laaru (Larawa)", "Lakka", "Lala", "Lama", "Lamja", "Lau", "Liptako", "Lopa (Lupa)", "Longuda (Lunguda)",
    "Mabo", "Mada", "Mama", "Mambilla", "Manchok", "Mandara (Wandala)", "Manga (Mangawa)", "Margi (Marghi)",
    "Matakam", "Mbembe", "Mbol", "Mbube", "Mbula", "Mbum", "Memyang (Meryan)", "Miango", "Miligili (Migili)",
    "Miya (Miyawa)", "Mobber", "Montol", "Moruwa (Moro'a, Morwa)", "Muchaila", "Mumuye", "Mundang",
    "Mupun", "Mushere", "Mwahavul (Mwaghavul)", "Ndoro", "Ngamo", "Ngizim", "Mbe", "Ngemai", "Ningi (Ningawa)",
    "Ninzam (Ninzo)", "Njayi", "Nkim", "Nkum", "Nokere (Nakere)", "Nunn", "Nupe", "Nyandang", "Ododop",
    "Ogori", "Okobo", "Okpamheri", "Olulumo", "Oron", "Owan", "Owe", "Oworo", "Pa'a (Pa'awa)", "Pai",
    "Panyam", "Pero", "Pire", "Pkanzom", "Poll", "Polchi Habe", "Pongo (Pongu)", "Potopo", "Pyem (Pyam)",
    "Reshe", "Ribina (Rebina)", "Robumba", "Rumada", "Rumaya", "Sakbe", "Sanga", "Sate", "Saya (Sayawa, Zaar)",
    "Segidi (Sigidawa)", "Shanga (Shangawa)", "Shangawa (Shanjo)", "Shira (Shirawa)", "Shomo", "Shuwa",
    "Sikdi", "Siri (Sirawa)", "Srubu (Surubu)", "Suku", "Sura", "Tangale", "Tarok", "Teme", "Tera (Terawa)",
    "Teshena (Teshenawa)", "Tiv", "Tula", "Tur", "Ubbo", "Udege", "Udogawa", "Urhobo", "Utonkon", "Uyanga",
    "Vimtim", "Uneme (Ineme)", "Ura (Ula)", "Uzem", "Verre", "Vommi", "Wagga", "Waja", "Waka", "Warja (Warja)",
    "Warji", "Wula (Wulawa)", "Wurbo", "Wurkun", "Yache", "Yagba", "Yakurr (Yako)", "Yalla", "Yandang",
    "Yergan (Yergum)", "Yernai", "Yolwa", "Yoruba", "Yukam", "Yungur", "Yuom", "Zabara", "Zaranda",
    "Zarma (Garma)", "Zayam (Zeem)", "Zul (Zulawa)"
].sort();
